# Generated by Django 6.0 on 2025-12-16 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese_word', models.CharField(max_length=100)),
                ('hiragana', models.CharField(blank=True, max_length=100, null=True)),
                ('katakana', models.CharField(blank=True, max_length=100, null=True)),
                ('meaning', models.TextField()),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('translation_sentence', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Words',
            },
        ),
    ]
