# Generated by Django 6.0 on 2025-12-19 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='word',
            name='example_sentence',
        ),
        migrations.RemoveField(
            model_name='word',
            name='katakana',
        ),
        migrations.RemoveField(
            model_name='word',
            name='translation_sentence',
        ),
        migrations.AddField(
            model_name='word',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='saved_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='topic',
            field=models.CharField(default='Umumiy', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='hiragana',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
