# Generated by Django 6.0 on 2025-12-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_remove_word_created_by_remove_word_example_sentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_game_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='recovery_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='tree_state',
            field=models.IntegerField(default=1),
        ),
    ]
