# Generated by Django 6.0 on 2026-01-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_profile_daily_games_played_profile_last_game_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='daily_games_played',
            new_name='daily_match_count',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='recovery_progress',
            new_name='daily_test_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_write_count',
            field=models.IntegerField(default=0),
        ),
    ]
