# Generated by Django 6.0 on 2026-01-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_rename_daily_games_played_profile_daily_match_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='topic',
        ),
        migrations.AlterField(
            model_name='word',
            name='hiragana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='words', to='vocabulary.topic'),
        ),
    ]
