# Generated by Django 6.0.1 on 2026-01-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0007_userwordprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="coins",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weeklystats",
            name="coins_earned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weeklystats",
            name="is_collected",
            field=models.BooleanField(default=False),
        ),
    ]
