# Generated by Django 6.0.1 on 2026-01-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0009_book_topic_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField(unique=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="league",
            field=models.CharField(
                choices=[
                    ("Bronze", "Bronze"),
                    ("Silver", "Silver"),
                    ("Gold", "Gold"),
                    ("Platinum", "Platinum"),
                    ("Diamond", "Diamond"),
                ],
                default="Bronze",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="weeklystats",
            name="xp_earned",
            field=models.IntegerField(default=0),
        ),
    ]
