# Generated by Django 5.1.4 on 2025-01-16 11:39

from django.db import migrations

def create_initial_badges(apps, schema_editor):
    Badge = apps.get_model('vocabulary', 'Badge')

    badges = [
        {
            'name': 'Ilk Qadam',
            'description': "Birinchi so'zni qo'shdingiz!",
            'icon': 'bi-flag-fill',
            'color': 'text-primary',
            'badge_type': 'words',
            'threshold': 1
        },
        {
            'name': 'Bilimdon',
            'description': "100 ta so'z yodladingiz!",
            'icon': 'bi-book-half',
            'color': 'text-info',
            'badge_type': 'words',
            'threshold': 100
        },
        {
            'name': 'Istiqbolli',
            'description': "7 kunlik uzluksiz o'qish!",
            'icon': 'bi-fire',
            'color': 'text-danger',
            'badge_type': 'streak',
            'threshold': 7
        },
        {
            'name': 'Chempion',
            'description': "Ligada 1-o'rinni egalladingiz!",
            'icon': 'bi-trophy-fill',
            'color': 'text-warning',
            'badge_type': 'league',
            'threshold': 1
        }
    ]

    for badge_data in badges:
        if not Badge.objects.filter(name=badge_data['name']).exists():
            Badge.objects.create(**badge_data)

def remove_initial_badges(apps, schema_editor):
    Badge = apps.get_model('vocabulary', 'Badge')
    names = ['Ilk Qadam', 'Bilimdon', 'Istiqbolli', 'Chempion']
    Badge.objects.filter(name__in=names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0011_badge_userbadge'),
    ]

    operations = [
        migrations.RunPython(create_initial_badges, remove_initial_badges),
    ]
