# Generated by Django 6.0.1 on 2026-01-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0012_populate_badges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("words", "Word Count"),
                    ("streak", "Daily Streak"),
                    ("league", "League Rank"),
                    ("coins", "Total Coins"),
                    ("books", "Saved Books"),
                    ("master", "Mastered Words"),
                    ("correct", "Correct Answers"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
