# Generated by Django 5.1.4 on 2025-01-16 12:00

from django.db import migrations

def create_new_badges(apps, schema_editor):
    Badge = apps.get_model('vocabulary', 'Badge')

    badges = [
        {
            'name': 'Mergan',
            'description': "100 ta to'g'ri javob topdingiz!",
            'icon': 'bi-crosshair',
            'color': 'text-danger',
            'badge_type': 'correct',
            'threshold': 100
        },
        {
            'name': 'Boyvachcha',
            'description': "1000 Coin yig'dingiz!",
            'icon': 'bi-cash-stack',
            'color': 'text-success',
            'badge_type': 'coins',
            'threshold': 1000
        },
        {
            'name': 'Kitobxon',
            'description': "3 ta kitobni saqlab qo'ydingiz!",
            'icon': 'bi-book-fill',
            'color': 'text-primary',
            'badge_type': 'books',
            'threshold': 3
        },
        {
            'name': 'Poliglot',
            'description': "50 ta so'zni Master qildingiz!",
            'icon': 'bi-translate',
            'color': 'text-info',
            'badge_type': 'master',
            'threshold': 50
        }
    ]

    for badge_data in badges:
        if not Badge.objects.filter(name=badge_data['name']).exists():
            Badge.objects.create(**badge_data)

def remove_new_badges(apps, schema_editor):
    Badge = apps.get_model('vocabulary', 'Badge')
    names = ['Mergan', 'Boyvachcha', 'Kitobxon', 'Poliglot']
    Badge.objects.filter(name__in=names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0013_alter_badge_badge_type'),
    ]

    operations = [
        migrations.RunPython(create_new_badges, remove_new_badges),
    ]
