# Generated by Django 5.1.4 on 2026-02-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0015_siteconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Kitob muqovasi rasmining havolasi (URL)",
                null=True,
            ),
        ),
    ]
